baseURL = "https://pornographyforposterity.com/"
languageCode = "en-us"
title = "Pornography for Posterity"
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    mainpagetitle = "PFP"
    mainpagesubtitle = "Ensuring Anthropological Preservation of Pornographic Media"
    mainpagedesc = "Click on the links above for more information, or to the right to jump to specific pages."
    copyrightname = "PornographyForPosterity.com"
    loadfastload = true

[taxonomies]
studio = "studio"
performer = "performers"
tags = "tags"
categories = "categories"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About PFP" # A display name for the button
    url = "/about/" # The path to the content. It can lead to a single page (like here)
    weight = 10 # A number to order the buttons in the navbar
